### ISSUE TITLE
not work on MindSpore (python3.8-cann8.0.rc1.beta1-mindspore2.3.0rc1-openmind0.7.1)

### ISSUE THREAD

**Issue by LronDC** [mindspore-lab/mindone#693]
## Hardware Environment | 硬件环境
    - [x] `Ascend`
    - [ ] `GPU`
    - [ ] `CPU`

### Software Environment | 软件环境

MindSpore (python3.8-cann8.0.rc1.beta1-mindspore2.3.0rc1-openmind0.7.1)

## Describe the current behavior | 目前输出
cannot import name 'mint' from 'mindspore' (/usr/local/python3.8/lib/python3 ……

## Describe the expected behavior | 期望输出
/

## Steps to reproduce the issue | 复现报错的步骤
from mindone.diffusers import StableVideoDiffusionPipeline

## Related log / screenshot | 完整日志

<img width="1469" alt="企业微信截图_9cda7b46-296f-4875-9d81-f8df4e461eb5" src="https://github.com/user-attachments/assets/db13550c-bcbc-431f-bcf4-3ac8332ff515">

## Special notes for this issue | 其他信息

补充背景：我运行在 modelers 空间中，所以基础镜像我没有其他选择，我希望在 npu 上跑 svd，于是用到了 mindone 中的 diffusers 模块来代替hf diffusers

问题： 
1. 是 ms 2.3.0 的兼容性问题吗
2. 有没有办法绕过
3. 能不能用 hf diffusers 在 mindspore 上

**Comment by Songyuanwei** [comment]
根据您登记的mindspore和报错日志显示，mindspore2.3.0rc1不支持mint算子，该算子在ms2.3.0及更新的版本才有提供，mindspore2.3.0rc1是ms2.3.0以前的版本，请尝试使用新版本

**Comment by townwish4git** [comment]
> ![image](https://private-user-images.githubusercontent.com/55976303/376181188-9e37b7ce-7035-4e18-bd64-8e83d5fc4018.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NjAzMTUsIm5iZiI6MTcyODk2MDAxNSwicGF0aCI6Ii81NTk3NjMwMy8zNzYxODExODgtOWUzN2I3Y2UtNzAzNS00ZTE4LWJkNjQtOGU4M2Q1ZmM0MDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDAyNDAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YzViMTA4MmFjMDI4YTM0MTU2ODk5NmU1OTM2YjQyYmQ2OWRhYjJhMGRlZGVjM2FiMjQyN2JlMjMzMGE2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GSn4Pb0juhSm8uOlx1qA9WC7gzjxol-chcb147vdIsQ) 使用此镜像MindSpore (python3.9-mindspore2.3.1-openmind0.8.0)，可解

您好，作为一个快速解决的方案：您可以参照@chenyang的方法选择ms2.3.0之后版本的镜像（ms2.3.0rc1是其**之前**版本）。

**P.S.** mindone.diffusers v0.29版本基于ms2.3.0+开发，未在其之前的mindspore版本进行过测试和验证。关于此issue，我们在 #695 进行了简单的修改以支持mindspore版本的向后兼容，该PR合入后您现有的环境下的此问题应该能够得以解决，但需要注意的是仍然无法保证mindone.diffusers v0.29在ms2.3.0之前版本的完整支持。
